# Generated by Django 5.0.7 on 2024-08-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
                ('street', models.CharField(max_length=255, verbose_name='Sokak')),
                ('building_number', models.CharField(max_length=10, verbose_name='Bina Numarası')),
                ('floor', models.CharField(max_length=10, verbose_name='Kat')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posta Kodu')),
                ('country', models.CharField(default='Turkey', max_length=100, verbose_name='Ülke')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
