# Generated by Django 5.0.7 on 2024-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('mineralwater', 'Mineral Water'), ('waterjug', 'Water Jug'), ('waterpet', 'Water Pet')], max_length=100),
        ),
    ]
