# Generated by Django 5.0.7 on 2024-08-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(max_length=10, verbose_name='Building Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Turkey', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(max_length=10, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
