# Generated by Django 5.0.7 on 2024-07-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0002_alter_category_description_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
