# Generated by Django 5.0.7 on 2024-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0003_alter_address_building_number_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
