# Generated by Django 5.0.7 on 2024-07-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0004_remove_orderitem_product_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
