# Generated by Django 5.0.7 on 2024-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0007_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
