# Generated by Django 5.0.7 on 2024-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0007_remove_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
