# Generated by Django 5.0.7 on 2024-07-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0009_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
