# Generated by Django 5.0.7 on 2024-08-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0011_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
    ]
