# Generated by Django 5.0.7 on 2024-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0012_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
