# Generated by Django 5.0.7 on 2024-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproject', '0013_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Türkiye', max_length=100, verbose_name='Country'),
        ),
    ]
